Update flake8
Was getting error `"pyflakes[F]" failed during execution due to
AttributeError("module 'ast' has no attribute 'Str'")` because ast.Str
has been deprecated and is no longer in python 3.14+, see
https://docs.python.org/dev/whatsnew/3.14.html#id9.

Using version 7.3.0 of flake8 now which updates all dependencies to
support python 3.14